#include "Mat.h"

IMPLEMENT_META( XE::Mat2x2f );
IMPLEMENT_META( XE::Mat2x3f );
IMPLEMENT_META( XE::Mat2x4f );
IMPLEMENT_META( XE::Mat3x2f );
IMPLEMENT_META( XE::Mat3x3f );
IMPLEMENT_META( XE::Mat3x4f );
IMPLEMENT_META( XE::Mat4x2f );
IMPLEMENT_META( XE::Mat4x3f );
IMPLEMENT_META( XE::Mat4x4f );

IMPLEMENT_META( XE::Mat2x2d );
IMPLEMENT_META( XE::Mat2x3d );
IMPLEMENT_META( XE::Mat2x4d );
IMPLEMENT_META( XE::Mat3x2d );
IMPLEMENT_META( XE::Mat3x3d );
IMPLEMENT_META( XE::Mat3x4d );
IMPLEMENT_META( XE::Mat4x2d );
IMPLEMENT_META( XE::Mat4x3d );
IMPLEMENT_META( XE::Mat4x4d );